version: "3.9"

services:
  mydb:
    container_name: mydb
    build:
      context: .
      dockerfile: elastic.Dockerfile 
    environment:
      - node.name=mydb
      - cluster.name=mydb
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./database:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    environment:
      ELASTICSEARCH_HOSTS: http://mydb:9200
      ES_USER: tests
      ES_GROUP: tests
    ports:
      - 5601:5601
    depends_on:
      - mydb