version: "3.9"

services:
  elasticdb:
    container_name: elasticdb
    build:
      context: .
      dockerfile: elastic.Dockerfile 
    environment:
      - node.name=elasticdb
      - cluster.name=elasticdb
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./database:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - yournetworkname

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    environment:
      ELASTICSEARCH_HOSTS: http://elasticdb:9200
      ES_USER: tests
      ES_GROUP: tests
    ports:
      - 5601:5601
    depends_on:
      - elasticdb
    networks:
      - yournetworkname

networks:
  yournetworkname:
    external: true

#Kibana http://localhost:5601/ (host)
#Inside Docker http://elasticdb:9200
#Outside Docker http://localhost:9200
